const C=window.TASKVN_CONFIG;
const sb=C&&!C.SUPABASE_URL.includes("YOUR-")?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY):null;
const $=s=>document.querySelector(s);let user=null,me=null;
const titles={dashboard:"Tổng quan",tasks:"Nhiệm vụ",claims:"Duyệt nhiệm vụ",proofs:"Duyệt ảnh Review",users:"Người dùng",admins:"Quản lý Admin",topups:"Nạp tiền",payouts:"Auto Payout",withdrawals:"Rút tiền",fraud:"Chống gian lận",ai:"TASKVN AI",web2:"Web 2",levels:"Cấp & EXP",ledger:"Ledger",settings:"Cài đặt"};
async function boot(){if(!sb){$("#status").textContent="Chưa cấu hình backend";show("dashboard");return}const r=await sb.auth.getUser();user=r.data.user;if(!user){$("#status").textContent="Chưa đăng nhập";return}let q=await sb.from("profiles").select("role,is_owner,display_name,email").eq("id",user.id).single();me=q.data;if(!me||me.role!=="admin"){document.body.innerHTML="<h2 style='padding:40px'>403 — Không có quyền admin</h2>";return}$("#status").textContent=me.is_owner?"OWNER / ADMIN":"ADMIN";show("dashboard")}
function card(x){return `<div class="card">${x}</div>`}
async function show(tab){
 $("#title").textContent=titles[tab]||tab;let h="";
 if(tab==="dashboard")h=card(`<div class="grid"><div><span class="muted">Người dùng</span><div class="num" id="sUsers">…</div></div><div><span class="muted">Claims</span><div class="num" id="sClaims">…</div></div><div><span class="muted">Chờ duyệt</span><div class="num" id="sPending">…</div></div><div><span class="muted">Rút chờ xử lý</span><div class="num" id="sWithdraw">…</div></div></div><p class="muted">Luồng: Verification → Risk Engine → Ledger → Payout.</p>`);
 else if(tab==="tasks")h=card(`<h3>🎯 Quản lý nhiệm vụ</h3><input class="field" id="taskTitle" placeholder="Tên nhiệm vụ"><input class="field" id="taskDesc" placeholder="Mô tả"><input class="field" id="taskReward" type="number" placeholder="Reward coin"><input class="field" id="taskProvider" placeholder="Provider"><input class="field" id="taskUrl" placeholder="URL"><select class="field" id="taskType"><option value="code">Code</option><option value="review">Review Map</option></select><button class="action" onclick="createTask()">Tạo nhiệm vụ</button><div id="taskList">Đang tải...</div>`);
 else if(tab==="claims")h=card(`<h3>🧾 Claims cần kiểm tra</h3><div id="claimList">Đang tải...</div>`);
 else if(tab==="proofs")h=card(`<h3>🖼️ Review Map</h3><div id="proofList">Đang tải...</div>`);
 else if(tab==="users")h=card(`<h3>👥 Người dùng</h3><div id="userList">Đang tải...</div>`);
 else if(tab==="admins")h=card(`<h3>👑 Admin chính / phụ</h3><p class="muted">Chỉ Owner được cấp/thu hồi Admin.</p><input class="field" id="adminEmail" placeholder="Email tài khoản đã đăng ký"><input class="field" id="adminName" placeholder="Tên hiển thị"><button class="action" onclick="createAdmin()">Cấp quyền Admin</button><div id="adminList">Đang tải...</div>`);
 else if(tab==="topups")h=card(`<h3>💳 Nạp tiền</h3><div id="topupList">Đang tải...</div>`);
 else if(tab==="payouts")h=card(`<h3>💰 Auto Payout</h3><p class="muted">Claim code hợp lệ + risk thấp có thể cộng ngay. Review Map sau khi duyệt sẽ có payout_at = 4 ngày.</p><button class="action" onclick="toast('Payout queue được xử lý server-side')">Kiểm tra</button>`);
 else if(tab==="withdrawals")h=card(`<h3>💸 Rút tiền</h3><p class="muted">Yêu cầu rút bị trừ giữ chỗ bằng transaction. Admin duyệt trạng thái; payout provider xử lý ở server.</p><div id="withdrawList">Đang tải...</div>`);
 else if(tab==="fraud")h=card(`<h3>🛡️ Risk Engine</h3><p>0–29: bình thường</p><p>30–69: theo dõi</p><p>70–89: manual review</p><p>90+: giữ payout</p><p class="muted">Có thể mở rộng với tốc độ claim, callback lặp, IP hash, device signals và tỷ lệ reject.</p>`);
 else if(tab==="ai")h=card(`<h3>🤖 TASKVN AI</h3><p class="muted">Bật/tắt AI, chỉnh lời chào và giới hạn.</p><label>Trạng thái</label><select class="field" id="aiEnabled"><option value="true">Bật</option><option value="false">Tắt</option></select><input class="field" id="aiGreeting" value="Xin chào! Mình là TASKVN AI."><button class="action" onclick="saveAI()">Lưu cấu hình</button>`);
 else if(tab==="web2")h=card(`<h3>🛍️ Web 2</h3><p class="muted">Web 2 là hệ thống shop/dịch vụ riêng. Không nhúng dữ liệu shop vào Web chính. Admin có thể kiểm tra URL và cấu hình chuyển coin theo backend.</p><input class="field" id="web2url" placeholder="URL Web 2"><button class="action" onclick="saveSetting('web2_url',$('#web2url').value)">Lưu URL</button>`);
 else if(tab==="levels")h=card(`<h3>🏆 Cấp độ & EXP</h3><p class="muted">Cấu hình mốc EXP và reward theo cấp. Không sửa số dư trực tiếp ở frontend.</p><input class="field" id="levelRules" placeholder="Ví dụ: 0:1,1000:2,5000:3"><button class="action" onclick="saveSetting('level_rules',$('#levelRules').value)">Lưu</button>`);
 else if(tab==="ledger")h=card(`<h3>📒 Ledger</h3><div id="ledgerList">Đang tải...</div>`);
 else h=card(`<h3>⚙️ Cài đặt</h3><input class="field" id="risk" value="70" placeholder="Risk threshold"><input class="field" id="reviewDays" value="4" placeholder="Review delay days"><button class="action" onclick="saveSetting('risk_threshold',$('#risk').value);saveSetting('review_delay_days',$('#reviewDays').value)">Lưu</button>`);
 $("#content").innerHTML=h;
 if(tab==="dashboard")loadDashboard();if(tab==="tasks")loadTasks();if(tab==="claims")loadClaims();if(tab==="proofs")loadProofs();if(tab==="users")loadUsers();if(tab==="admins")loadAdmins();if(tab==="topups")loadTopups();if(tab==="withdrawals")loadWithdrawals();if(tab==="ledger")loadLedger();
}
async function rows(table,select="*"){const r=await sb.from(table).select(select);if(r.error)throw r.error;return r.data||[]}
async function loadDashboard(){try{$("#sUsers").textContent=(await rows("profiles","id")).length;$("#sClaims").textContent=(await rows("task_claims","id")).length;$("#sPending").textContent=(await rows("task_proofs","id")).filter(x=>x.status==="pending").length;$("#sWithdraw").textContent=(await rows("withdrawals","id")).filter(x=>["pending","risk_review","processing"].includes(x.status)).length}catch(e){toast(e.message)}}
async function loadTasks(){try{const a=await rows("tasks","id,title,reward,status,task_type,created_at");$("#taskList").innerHTML=a.map(t=>`<div class="admin-row"><b>${esc(t.title)}</b><span>${Number(t.reward).toLocaleString("vi-VN")} · ${t.task_type} · ${t.status}</span></div>`).join("")||"Chưa có nhiệm vụ."}catch(e){$("#taskList").textContent=e.message}}
async function createTask(){try{const t={title:$("#taskTitle").value.trim(),description:$("#taskDesc").value.trim(),reward:Number($("#taskReward").value),provider:$("#taskProvider").value.trim()||"internal",url:$("#taskUrl").value.trim()||"#",task_type:$("#taskType").value,status:"active"};if(!t.title||!t.reward)return toast("Thiếu tên/reward");const r=await sb.from("tasks").insert(t);if(r.error)throw r.error;toast("Đã tạo");loadTasks()}catch(e){toast(e.message)}}
async function loadClaims(){const a=await rows("task_claims","id,user_id,task_id,status,risk_score,reward,created_at");$("#claimList").innerHTML=a.filter(x=>["manual_review","pending_verification"].includes(x.status)).map(c=>`<div class="card"><b>${c.id}</b><p>User: ${c.user_id}<br>Risk: ${c.risk_score}<br>Reward: ${c.reward}<br>Status: ${c.status}</p><button class="action" onclick="approveClaim('${c.id}')">Duyệt</button></div>`).join("")||"Không có claim chờ."}
async function approveClaim(id){const{data,error}=await sb.functions.invoke("verify-code",{body:{claim_id:id,code:""}});if(error)toast(error.message);else toast(data?.status||"Đã xử lý")}
async function loadProofs(){const a=await rows("task_proofs","id,claim_id,user_id,storage_path,status,created_at");$("#proofList").innerHTML=a.filter(x=>x.status==="pending").map(p=>`<div class="card"><b>Claim:</b> ${p.claim_id}<br><b>User:</b> ${p.user_id}<br><button class="action" onclick="approveProof('${p.id}','${p.claim_id}')">Duyệt</button> <button class="danger" onclick="rejectProof('${p.id}')">Từ chối</button></div>`).join("")||"Không có ảnh chờ duyệt."}
async function approveProof(id,claim){const{data,error}=await sb.functions.invoke("approve-review",{body:{proof_id:id,claim_id:claim}});if(error)toast(error.message);else{toast(data?.message||"Đã duyệt");loadProofs()}}
async function rejectProof(id){const note=prompt("Lý do?")||"Không đạt";const{error}=await sb.from("task_proofs").update({status:"rejected",admin_note:note,reviewed_at:new Date().toISOString()}).eq("id",id);if(error)toast(error.message);else loadProofs()}
async function loadUsers(){const a=await rows("profiles","id,email,display_name,role,balance,level,exp,created_at");$("#userList").innerHTML=a.slice(0,100).map(u=>`<div class="admin-row"><b>${esc(u.email||u.id)}</b><span>${u.role} · ${Number(u.balance).toLocaleString("vi-VN")} coin · Lv.${u.level||1}</span></div>`).join("")}
async function loadAdmins(){const{data,error}=await sb.functions.invoke("admin-management",{body:{action:"list"}});if(error)return $("#adminList").textContent=error.message;$("#adminList").innerHTML=(data?.admins||[]).map(a=>`<div class="admin-row"><b>${esc(a.email||"—")}</b><span>${a.is_owner?"OWNER":"ADMIN"}</span>${!a.is_owner?`<button class="danger" onclick="revokeAdmin('${a.id}')">Thu hồi</button>`:""}</div>`).join("")||"Chưa có Admin phụ."}
async function createAdmin(){const email=$("#adminEmail").value.trim();if(!email)return toast("Nhập email");const{data,error}=await sb.functions.invoke("admin-management",{body:{action:"create",email,display_name:$("#adminName").value.trim()}});if(error)toast(error.message);else{toast(data?.message||"Đã cấp quyền");loadAdmins()}}
async function revokeAdmin(id){if(!confirm("Thu hồi Admin?"))return;const{data,error}=await sb.functions.invoke("admin-management",{body:{action:"revoke",user_id:id}});if(error)toast(error.message);else{toast(data?.message||"Đã thu hồi");loadAdmins()}}
async function loadTopups(){const a=await rows("topups","id,user_id,amount,transfer_code,status,created_at");$("#topupList").innerHTML=a.filter(x=>x.status==="pending").map(t=>`<div class="card"><b>${Number(t.amount).toLocaleString("vi-VN")}đ</b><p>${t.transfer_code}<br>User: ${t.user_id}</p><button class="action" onclick="approveTopup('${t.id}')">Đã nhận → Cộng</button> <button class="danger" onclick="rejectTopup('${t.id}')">Từ chối</button></div>`).join("")||"Không có yêu cầu."}
async function approveTopup(id){if(!confirm("Chỉ xác nhận sau khi đối soát giao dịch thật."))return;const{data,error}=await sb.rpc("approve_topup",{p_topup_id:id,p_note:"Admin đối soát"});if(error)toast(error.message);else{toast("Đã cộng");loadTopups()}}
async function rejectTopup(id){const note=prompt("Lý do?")||"Không xác nhận được";const{error}=await sb.rpc("reject_topup",{p_topup_id:id,p_note:note});if(error)toast(error.message);else loadTopups()}
async function loadWithdrawals(){const a=await rows("withdrawals","id,user_id,amount,method,receiver,status,risk_score,created_at");$("#withdrawList").innerHTML=a.filter(x=>!["paid","rejected"].includes(x.status)).map(w=>`<div class="card"><b>${Number(w.amount).toLocaleString("vi-VN")} coin</b><p>${w.method} · ${esc(w.receiver)}<br>Risk: ${w.risk_score} · ${w.status}</p><button class="action" onclick="setWithdrawal('${w.id}','approved')">Duyệt</button> <button class="danger" onclick="setWithdrawal('${w.id}','rejected')">Từ chối</button></div>`).join("")||"Không có yêu cầu."}
async function setWithdrawal(id,status){const note=status==="rejected"?(prompt("Lý do?")||"Từ chối"):"Admin duyệt";const{data,error}=await sb.rpc("admin_set_withdrawal",{p_id:id,p_status:status,p_note:note});if(error)toast(error.message);else{toast(data?"Đã cập nhật":"Không thể cập nhật");loadWithdrawals()}}
async function loadLedger(){const a=await rows("ledger","id,user_id,amount,type,idempotency_key,created_at");$("#ledgerList").innerHTML=a.slice(-100).reverse().map(x=>`<div class="admin-row"><span>${x.type}</span><b>${Number(x.amount).toLocaleString("vi-VN")}</b><small>${x.user_id}</small></div>`).join("")||"Chưa có ledger."}
async function saveAI(){await saveSetting("ai_enabled",$("#aiEnabled").value);await saveSetting("ai_greeting",$("#aiGreeting").value);toast("Đã lưu AI")}
async function saveSetting(k,v){if(!sb)return;const{error}=await sb.from("app_settings").upsert({key:k,value:JSON.stringify(v)});if(error)toast(error.message);else toast("Đã lưu")}
function toast(t){alert(t)}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.querySelectorAll("aside button").forEach(b=>b.onclick=()=>show(b.dataset.tab));boot();
